### ISSUE TITLE
Using trace

### ISSUE THREAD

**Issue by probins** [ModuleLoader/es-module-loader#515]
I would like to make use of this in the register loader, but can't work out how. There doesn't seem to be any ability to set `trace=true` in a constructor option, but if I set it on the instance, I get an error 'Tracing error, ensure loader.trace is set before loading' and the load fails:

``` js
var loader = new window.SystemRegisterLoader(document.baseURI);
loader.trace=true;
```

Does this mean I have to create a special tracing loader inheriting from the registerLoader or something?

**Comment by guybedford** [comment]
If I edit the example browser.html file in the system-register-loader project to have `loader.trace = true` set immediately after construction this works fine.

It would only happen like that if `trace = false` is changed to `trace = true` after already loading a module, but if the loader hasn't loaded any modules yet it shouldn't show that error.

**Comment by probins** [comment]
try importing a more meaningful test that includes an import:

testimport.js:
``` js
System.register(['./register.js'], function (_export, _context) {
  var hello;
  return {
    setters: [function (_registerJs) {
      hello = _registerJs.hello;
    }],
    execute: function () {
      console.log(hello); // -> world
    }
  };
});
```

**Comment by guybedford** [comment]
Thanks, yes there was a bug here. I've fixed it up now.

**Comment by probins** [comment]
this works now on a simple test, but I'm still getting errors on my much larger app. Behaves differently though: before it was failing on the first load, now it's getting through most of them but failing on some. I'll see if I can work out under what circumstances it fails

**Comment by guybedford** [comment]
@probins if you can even just share the error message that would help too.

**Comment by probins** [comment]
same error msg 'ensure loader.trace is set before loading'. Wouldn't spend too much time on it; there are other npm pkgs for generating a dependency tree, even creating pretty diagrams.

**Comment by guybedford** [comment]
It may be because you are legitimately using a custom instantiate hook, which will therefore be not included in the trace.

It may be worth just not throwing this error at all though.

**Comment by probins** [comment]
I'm not using any custom hooks at all, just standard import/export (all defaults) converted into System.register. I do have various `loader.import()`s in event listeners - might it be trying to do something with those? I don't think I have any circular refs. I can try disabling the error and see what happens.

**Comment by guybedford** [comment]
Race conditions would always be good to know about :)

**Comment by probins** [comment]
some more info: if I put in a breakpoint, the failing modules are failing the 3rd condition - `dependencies` exists but `depMap` does not. The modules concerned load correctly but are not in `loader.loads`. If I comment out the throw, the records are present in `loads` but missing `depMap`. I assume that these two properties should be the same, just one is an array and the other an object. Does that help?

**Comment by guybedford** [comment]
@probins yes this does sound like an unexpected state then as `depMap` should always be defined by the time we get to trace. Is there any way you can share this test case further?

**Comment by guybedford** [comment]
This may be fixed by https://github.com/ModuleLoader/es-module-loader/commit/a65b28716e9841a587cb19d109410ab85543f4ab.

**Comment by probins** [comment]
could you issue another release on npm? I'm maintaining a git clone of system-register-loader. I tried `npm update`, but this loaded 1.1.0 of es-module-loader which seems to be an entirely different package. So I deleted node_modules and ran `npm install`. This loads 1.0.3, but this doesn't include the latest commits.

**Comment by guybedford** [comment]
Sure I've done a release cycle.

**Comment by probins** [comment]
yes, I no longer get the errors when I set trace=true, and `loads` seems to be correct. My app no longer works though with trace=true, so it seems to be an either/or: either trace or imports work normally. Not sure whether that's intentional or not, but I'll close this one again.

**Comment by guybedford** [comment]
@probins thanks for confirming. `trace` shouldn't affect the running of the app at all though. Are you sure it is only trace that is affecting this or could this be a break on the upgrade path?

**Comment by probins** [comment]
I built (and uglified) new system-register-loader, and installed: app works fine. Added trace=true:
``` js
var loader = new window.SystemRegisterLoader(document.baseURI);
loader.trace=true;
```
app no longer works (in some cases fails with js error, in others just doesn't do what it's supposed to).
Remove trace=true: app works fine again.

**Comment by guybedford** [comment]
@probins that's very odd. If you can't share a replication, perhaps you could try removing the branches at https://github.com/ModuleLoader/es-module-loader/blob/master/core/register-loader.js#L153 and https://github.com/ModuleLoader/es-module-loader/blob/master/core/register-loader.js#L440 and see if removing either of those checks makes a difference?

**Comment by probins** [comment]
commenting out the 2nd one causes it to fail even if trace is false. Commenting out 1st one works with trace false, but fails if true.

**Comment by guybedford** [comment]
But when trace is true the 2nd one will run? I mean commenting out the conditional `if` statement, not the code itself?

**Comment by guybedford** [comment]
So eg for the first case:

```javascript
//    if (!loader.trace)
      load.metadata = undefined;
```

**Comment by probins** [comment]
ah sorry. misunderstood.

**Comment by probins** [comment]
1st if commented leads -> same problem. 2nd if commented out -> previous 'trace must be set before loading' error.

**Comment by guybedford** [comment]
Are you using `<script type="module">` tags in the page or `loader.import`? I'm wondering if the module tags are running before the `trace` is set perhaps`. Otherwise you could also replacing that throw statement with a return statement and see if that avoids the issue?

**Comment by probins** [comment]
not using module scripts, but am using import() - a lot, as I use it for pre-loading dependencies, and also there are a lot of conditional imports (such as options from querystring). So it's very possible there's some kind of race condition or similar situation where several imports are loading the same dependency and something is getting confused. But everything works fine so long as trace isn't true.

**Comment by guybedford** [comment]
@probins do still let me know if you can share any replication here at all, would be good to narrow this down still.

**Comment by guybedford** [comment]
I've just published a 1.3 with a completely new linking algorithm. This would likely have been resolved in the process, but if it is still there please do post a new issue.

**Comment by probins** [comment]
ok, I'll take a look. Might take a while though, as I'm tied up with other things atm.

**Comment by probins** [comment]
just tried with 1.3 in system-register-loader. The previous errors have gone away, but setting trace=true is still causing the load to fail, this time with module not found errors; works fine with trace not set. ATM, as the production version works fine, I've not set up the ability on my system to load uncompressed source or source maps. I'll have to set this up the next time I do some development though, then it should be possible for you to load it and see if you can work out why this is failing. It's not a high priority for me, as I've used other tools to create dependency trees.
